name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=cover.out -v ./...
    - name: Code Climate Coverage Action
    # You may pin to the exact commit or the version.
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: db6b1a22f55faced27e0fc546607ee9c478b0e93f54062114e02ee89a9939a2e
      with:
        # Coverage command to execute
        coverageCommand: go tool cover -html cover.out 
