name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BINANCE_API_BASE_URL: https://test.api.binance.com
      COINGECKO_API_BASE_URL: https://api.coingecko.com/api/v3
      BINANCE_API_KEY: TESTAPIKEYABC123
      BINANCE_API_SECRET_KEY: TESTSECRETEAPIKEYAbc1234
      APP_NAME: Crypto-balancer
      PROGRAMMING_LANGUAGE: golang
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
