name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  release-linux-amd64:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://golang.org/dl/go1.16.darwin-amd64.tar.gz"
          project_path: "./cmd/test-binary"
          binary_name: "test-binary"
          extra_files: LICENSE README.md
